### PR TITLE
fix issue 33

### LINKED ISSUE #33: Making Biomart Object Failure
When a pre-specified biomart object is not given the get_biomart() function errors out.
I think the cause of this is that ENGS have the '.Version' attached which needs to be removed.

Issue : https://github.com/kelshmo/sageseqr/blob/2237c38d198951f47c9cbb4e6e62dcaddeb2d655/R/functions.R#L135

```
> head(gene_ids)
[1] "N_unmapped"        "N_multimapping"    "N_noFeature"       "N_ambiguous"       "ENSG00000223972.5" "ENSG00000227232.5"
> coords <- biomaRt::getBM(filters = id_type, attributes = attrs, values = gene_ids, mart = ensembl)
> head(coords)
[1] ensembl_gene_id  ensembl_exon_id  chromosome_name  exon_chrom_start exon_chrom_end  
<0 rows> (or 0-length row.names)
```
Potential Fix:
```
> foo <- as.character(do.call( rbind, strsplit( gene_ids,"[.]" ))[,1])
> head(foo)
[1] "N_unmapped"      "N_multimapping"  "N_noFeature"     "N_ambiguous"     "ENSG00000223972" "ENSG00000227232"
> coords <- biomaRt::getBM(filters = id_type, attributes = attrs, values = foo, mart = ensembl)
> head(coords)

  ensembl_gene_id ensembl_exon_id chromosome_name exon_chrom_start exon_chrom_end
1 ENSG00000263811 ENSE00002699344               1         16858949       16859021
2 ENSG00000252956 ENSE00002089424               1          9437669        9437778
3 ENSG00000253086 ENSE00002089554               1         11152350       11152452
4 ENSG00000207237 ENSE00001807736               1         25964197       25964300
5 ENSG00000263793 ENSE00002707582               1         23044305       23044372
6 ENSG00000206888 ENSE00001808772               1         27325219       27325325
```

### PR DESCRIPTION
**Pull request by kelshmo**
fixes #33 
- if, else statement in `parse_counts`should help skip the check and preserve computation time as it is kind of slow, checking row by row
- checks for rows that contain "N_" and removes them if there is a pattern match.
- checks in `get_biomart` so that function can be a stand-alone function
- checks in `filter_genes`. If the user downloads gene metadata from a Synapse file, they would bypass the check in `get_biomart`.
- Note: Transcript number (e.g. ENSG45xxxx.5) is parsed by `convert_geneids` called in `get_biomart`

### CODE REVIEW

**Comment by jgockley62** [comment]
Also super minor thing I noticed at the top of the biomart function
```
get_biomart <- function(count_df, gene_id, synid, version, host, filters, organism) {
  if (is.null(config::get("biomart")$synID)) {
    # Get available datset from Ensembl
    ensembl <- biomart_obj(organism, host)
```

Because it's inside of the function should ```config::get("biomart")$synID``` just be ```synid``` ?

**Comment by kelshmo** [comment]
@jgockley62 Your error is because your `count_df` object does not have rownames set with gene identifiers. The documentation for [this parameter](https://github.com/kelshmo/sageseqr/blob/94d63132b213c8fcc27f135b64d645c952afed6b/R/functions.R#L136) states this requirement. Upstream of `get_biomart` gene identifiers are set as rownames as a part of the cleaning process. 

Good catch with the biomart function. Will address in #43.

**Comment by jgockley62** [comment]
@kelshmo Pretty sure the counts data frame used for counts df has the gene ID as rownames
```
> import_metadata <- get_data(config::get("metadata")$synID, config::get("metadata")$version)         
> import_counts <- get_data(config::get("counts")$synID, config::get("counts")$version)   
> clean_md <- clean_covariates(md = import_metadata, factors = config::get("factors"),      continuous = config::get("continuous"))    
> counts <- tibble::column_to_rownames(import_counts, var = config::get("counts")$`gene id`)  
> head(row.names(counts))                       
[1] "N_unmapped"        "N_multimapping"    "N_noFeature"       "N_ambiguous"       "ENSG00000223972.5" "ENSG00000227232.5"
 ```  
 


--
 
```

**Comment by kelshmo** [comment]
I over complicated the function to the point of it not even suiting our use case! I was checking whether any possible column matched that pattern. 

I updated the function to only check row names and added tests.

**Pull request merged**
